# GitHub Actions Workflow para Build Móvel
# Jump and Hit - Automated Mobile Builds

name: Mobile Build

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Tipo de build'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  android-build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-mobile.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
          
    - name: Cache Buildozer local directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-local-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-local-
          
    - name: Instalar dependências do sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          cmake \
          libncurses5-dev \
          libncursesw5-dev \
          libedit-dev \
          libreadline6-dev \
          libsqlite3-dev \
          libssl-dev \
          libbz2-dev \
          libexpat1-dev \
          liblzma-dev \
          libffi-dev \
          uuid-dev
          
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Instalar dependências Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install buildozer cython
        
    - name: Verificar configuração
      run: |
        python --version
        java -version
        buildozer --version
        
    - name: Build Android Debug
      if: github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == ''
      run: |
        buildozer android debug
        
    - name: Build Android Release
      if: github.event.inputs.build_type == 'release'
      run: |
        buildozer android release
        
    - name: Listar arquivos gerados
      run: |
        echo "Conteúdo do diretório bin:"
        ls -la bin/ || echo "Diretório bin não encontrado"
        echo "\nTamanho dos APKs:"
        find . -name "*.apk" -exec ls -lh {} \;
        
    - name: Upload APK Debug
      if: github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == ''
      uses: actions/upload-artifact@v3
      with:
        name: jumpandhit-debug-apk
        path: bin/*debug*.apk
        retention-days: 30
        
    - name: Upload APK Release
      if: github.event.inputs.build_type == 'release'
      uses: actions/upload-artifact@v3
      with:
        name: jumpandhit-release-apk
        path: bin/*release*.apk
        retention-days: 90
        
    - name: Upload logs em caso de erro
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/build-*/logs/
          .buildozer/android/platform/python-for-android/
        retention-days: 7

  ios-build:
    name: Build iOS (macOS)
    runs-on: macos-latest
    if: false  # Desabilitado por enquanto - requer configuração adicional
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Instalar kivy-ios
      run: |
        pip install kivy-ios
        
    - name: Build iOS dependencies
      run: |
        toolchain build python3 kivy
        
    - name: Create iOS project
      run: |
        toolchain create JumpAndHit .
        
    - name: Upload iOS project
      uses: actions/upload-artifact@v3
      with:
        name: jumpandhit-ios-project
        path: JumpAndHit-ios/
        retention-days: 30

  # Job para criar release quando há tag
  create-release:
    name: Criar Release
    needs: [android-build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Download APK artifacts
      uses: actions/download-artifact@v3
      with:
        name: jumpandhit-debug-apk
        path: ./apks/
        
    - name: Criar Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./apks/*.apk
        body: |
          ## 📱 Jump and Hit - Mobile Release
          
          ### Android APK
          - **Debug APK**: Para testes e desenvolvimento
          - **Tamanho**: ~50MB
          - **Requisitos**: Android 5.0+ (API 21)
          
          ### ⚠️ Limitações
          - Pygame tem limitações no mobile
          - Performance pode ser limitada
          - Controles touch básicos
          
          ### 📋 Instalação
          1. Baixe o APK
          2. Habilite "Fontes desconhecidas" no Android
          3. Instale o APK
          
          ### 🐛 Problemas Conhecidos
          - Alguns dispositivos podem ter problemas de áudio
          - Performance varia entre dispositivos
          
          Para melhor experiência móvel, considere a versão desktop.
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}